// Verji custom Freshworks help-widget integration.
//
// We restyle the widget banner to Verji green by injecting a stylesheet into the
// widget's iframe document. The widget is a same-origin iframe whose internal DOM
// is generated by Freshworks and uses hashed CSS class names that change between
// widget releases — so the styling targets a stable Verji-owned class we attach
// ourselves, found via an ordered list of candidate selectors with safe fallbacks.

const VERJI_GREEN = "rgba(91, 150, 28, 1)";
const HEADER_CLASS = "verji-support-header";
const STYLE_ID = "verji-support-widget-styles";

// Tried in order. data-testid is what Freshworks uses for its own QA, so it
// tends to survive widget releases. The styled-components display-name prefix
// (WidgetHeader__Wrapper-sc-...) is a second hook in case the testid is
// renamed. If both miss, applyStyling logs the list once so we know what to
// add. The previously hardcoded hashed class (.dTKHQv) is intentionally gone:
// Freshworks already rebuilt it to .eSheGS, confirming hashed classes are
// disposable.
const HEADER_SELECTORS = [
    '[data-testid="header-wrapper"]',
    '[class*="WidgetHeader__Wrapper"]',
];

let outerObserver = null;
let innerObserver = null;

function toggleWidget() {
    const iframe = document.getElementById("widget-frame");
    if (iframe) {
        FreshworksWidget("close");
        cleanupObservers();
    } else {
        FreshworksWidget("open");
        waitForIframe();
    }
}

function cleanupObservers() {
    if (outerObserver) {
        outerObserver.disconnect();
        outerObserver = null;
    }
    if (innerObserver) {
        innerObserver.disconnect();
        innerObserver = null;
    }
}

function waitForIframe() {
    const existing = document.getElementById("widget-frame");
    if (existing) {
        bindIframe(existing);
        return;
    }

    outerObserver = new MutationObserver(() => {
        const iframe = document.getElementById("widget-frame");
        if (iframe) {
            outerObserver.disconnect();
            outerObserver = null;
            bindIframe(iframe);
        }
    });
    outerObserver.observe(document.body, { childList: true, subtree: true });

    setTimeout(() => {
        if (outerObserver) {
            outerObserver.disconnect();
            outerObserver = null;
            console.warn("[Verji] Support widget iframe never appeared; giving up on custom styling.");
        }
    }, 10000);
}

function bindIframe(iframe) {
    const attach = () => {
        let doc;
        try {
            doc = iframe.contentDocument || iframe.contentWindow.document;
        } catch (e) {
            console.warn("[Verji] Support widget iframe is cross-origin; cannot apply custom styling.", e);
            return;
        }
        if (!doc || !doc.body) {
            iframe.addEventListener("load", attach, { once: true });
            return;
        }
        applyStyling(doc);
        innerObserver = new MutationObserver(() => applyStyling(doc));
        innerObserver.observe(doc.body, { childList: true, subtree: true });
    };
    attach();
}

function applyStyling(doc) {
    if (doc.getElementById(STYLE_ID) && doc.querySelector("." + HEADER_CLASS)) {
        return true;
    }

    const header = findHeader(doc);
    if (!header) {
        if (!doc.__verjiSupportNoHeaderWarned) {
            console.warn(
                "[Verji] Support widget: header element not located. Selectors tried:",
                HEADER_SELECTORS,
            );
            doc.__verjiSupportNoHeaderWarned = true;
        }
        return false;
    }
    header.classList.add(HEADER_CLASS);

    let style = doc.getElementById(STYLE_ID);
    if (!style) {
        style = doc.createElement("style");
        style.id = STYLE_ID;
        doc.head.appendChild(style);
    }
    style.textContent = `.${HEADER_CLASS} { background: ${VERJI_GREEN} !important; }`;
    return true;
}

function findHeader(doc) {
    for (const sel of HEADER_SELECTORS) {
        try {
            const el = doc.querySelector(sel);
            if (el) return el;
        } catch (e) {
            // Invalid selector for this document — skip.
        }
    }
    return null;
}

function init() {
    window.fwSettings = {
        widget_id: 80000004505,
        locale: "nb-NO",
    };
    !(function () {
        if ("function" != typeof window.FreshworksWidget) {
            var n = function () {
                n.q.push(arguments);
            };
            (n.q = []), (window.FreshworksWidget = n);
        }
    })();
    FreshworksWidget("hide", "launcher");
}

init();
export default toggleWidget;
